import { readFile, writeFile, readdir } from 'node:fs/promises';
import { resolve, dirname } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

export const GUIDE_REVISION = 'mission-first-v1';
export const GUIDE_LANGUAGES = ['en', 'es', 'fr', 'de', 'pt', 'it', 'zh', 'ja'];
export const GUIDE_CATEGORIES = ['getting-started', 'missions', 'specs', 'pipeline', 'agents', 'insights', 'integrations', 'settings'];
const marker = `<!-- guide-revision: ${GUIDE_REVISION} -->`;
export function guideSlug(category, sourceSlug) {
  return category === 'getting-started' && sourceSlug === 'what-is-specrails' ? 'getting-started' : `${category}-${sourceSlug}`;
}
function metadata(content) {
  const title = content.match(/^# (.+)$/m)?.[1]?.trim();
  const description = content.replace(/<!--[\s\S]*?-->/g, '').split('\n').map(s => s.trim()).find(s => s && !s.startsWith('#'));
  if (!title || !description) throw new Error('Guide needs a title and opening description');
  return { title, description: description.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/[*_`]/g, ''), headings: [...content.matchAll(/^##+ (.+)$/gm)].map(m => m[1]) };
}
export async function buildGuideIndex(root) {
  const entries = [];
  const articles = [];
  for (const category of GUIDE_CATEGORIES) {
    const files = (await readdir(resolve(root, 'en', category))).filter(s => /^\d+-.+\.md$/.test(s)).sort((a,b) => a.localeCompare(b, 'en', {numeric:true}));
    for (const file of files) {
      const sourceSlug = file.replace(/^\d+-/, '').replace(/\.md$/, '');
      const entry = { key: `${category}/${file}`, slug: guideSlug(category, sourceSlug), sourceSlug, category, translations: {} };
      for (const language of GUIDE_LANGUAGES) {
        let content;
        try { content = await readFile(resolve(root, language, entry.key), 'utf8'); }
        catch (error) { if (error.code === 'ENOENT' && language !== 'en' && language !== 'es') continue; throw error; }
        if (!content.startsWith(marker)) {
          if (language === 'en' || language === 'es') throw new Error(`Stale required guide: ${language}/${entry.key}`);
          continue; // Stale translations never become the current product's instructions.
        }
        entry.translations[language] = metadata(content);
        articles.push({ key: `${language}/${entry.key}`, content });
      }
      entries.push(entry);
    }
  }
  const slugs = new Set(entries.map(e => e.slug));
  if (slugs.size !== entries.length) throw new Error('Duplicate documentation route');
  for (const {key, content} of articles) {
    for (const match of content.matchAll(/\]\((\/docs(?:\/[^)#?\s]*)?)[^)]*\)/g)) {
      if (match[1] !== '/docs' && !slugs.has(match[1].slice('/docs/'.length))) throw new Error(`Broken guide link in ${key}: ${match[1]}`);
    }
  }
  return { revision: GUIDE_REVISION, entries };
}
export function buildSitemap(index) {
  const paths = ['/', '/download', '/companion', '/privacy', '/docs', ...index.entries.map(e => `/docs/${e.slug}`)];
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${paths.map(path => `  <url><loc>https://specrails.dev${path}</loc></url>`).join('\n')}\n</urlset>\n`;
}
export function buildArticleLoaders(index) {
  const loaders = index.entries.flatMap(entry => Object.keys(entry.translations).map(language => {
    const key = `${language}/${entry.key}`;
    return `  ${JSON.stringify(key)}: () => import(${JSON.stringify(`../content/guide/${key}?raw`)}).then(module => module.default),`;
  }));
  return `// Generated by scripts/sync-guide.mjs; only current translations are shipped.\nexport const articleLoaders: Record<string, () => Promise<string>> = {\n${loaders.join('\n')}\n};\n`;
}
export async function syncGuide(projectRoot, check = false) {
  const index = await buildGuideIndex(resolve(projectRoot, 'src/content/guide'));
  for (const [file, expected] of [
    ['src/lib/docs-generated.json', `${JSON.stringify(index, null, 2)}\n`],
    ['public/sitemap.xml', buildSitemap(index)],
    ['src/lib/docs-loaders.ts', buildArticleLoaders(index)],
  ]) {
    const path = resolve(projectRoot, file);
    if (check) {
      let actual = ''; try { actual = await readFile(path, 'utf8'); } catch (e) { if (e.code !== 'ENOENT') throw e; }
      if (actual !== expected) throw new Error(`Outdated ${file}; run node scripts/sync-guide.mjs`);
    } else await writeFile(path, expected);
  }
  return index;
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
    const index = await syncGuide(root, process.argv.includes('--check'));
    console.log(`Guide ${process.argv.includes('--check') ? 'checked' : 'generated'}: ${index.entries.length} routes`);
  } catch (error) { console.error(error.message); process.exitCode = 1; }
}
